### ISSUE TITLE
DiseaseCaseDataControllerTest.addMinimalRequiredInformation:98 

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HpoCaseAnnotator#68]
Just encountered this:
```
[ERROR] Failures: 
[ERROR]   DiseaseCaseDataControllerTest.addMinimalRequiredInformation:98 
Expected: is <entrez_id: 3172
symbol: "HNF4A"
>
     but: was <>
[INFO] 
[ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 3
```

**Comment by ielis** [comment]
I am getting no errors when I run tests on Ubuntu. However, I am getting a weird behavior from tests that perform GUI testing (pointing, clicking, typing, ...) when running on OSX. There must be some issues with backend of the JavaFX testing framework used for testing.

This might be a pain in the back for a while, I am not sure how long will it take to figure out the cause. *Please package the software without running tests*. This should not be an issue since they are passing on Ubuntu and we're including executables within each release.
